import React from 'react';
import {View, Image, StyleSheet} from 'react-native';
import {PieceType, PieceColor} from '../game/chessLogic';

interface ChessPieceProps {
  type: PieceType;
  color: PieceColor;
}

// Map of piece images (generated by DALL-E 3)
const PIECE_IMAGES = {
  'white-king': require('../../assets/chess/pieces/white-king.png'),
  'white-queen': require('../../assets/chess/pieces/white-queen.png'),
  'white-rook': require('../../assets/chess/pieces/white-rook.png'),
  'white-bishop': require('../../assets/chess/pieces/white-bishop.png'),
  'white-knight': require('../../assets/chess/pieces/white-knight.png'),
  'white-pawn': require('../../assets/chess/pieces/white-pawn.png'),
  'black-king': require('../../assets/chess/pieces/black-king.png'),
  'black-queen': require('../../assets/chess/pieces/black-queen.png'),
  'black-rook': require('../../assets/chess/pieces/black-rook.png'),
  'black-bishop': require('../../assets/chess/pieces/black-bishop.png'),
  'black-knight': require('../../assets/chess/pieces/black-knight.png'),
  'black-pawn': require('../../assets/chess/pieces/black-pawn.png'),
};

const ChessPiece: React.FC<ChessPieceProps> = ({type, color}) => {
  const pieceKey = `${color}-${type}` as keyof typeof PIECE_IMAGES;

  return (
    <View style={styles.container}>
      <Image
        source={PIECE_IMAGES[pieceKey]}
        style={styles.pieceImage}
        resizeMode="contain"
      />
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pieceImage: {
    width: '85%',
    height: '85%',
  },
});

export default ChessPiece;
